In [2]:
import torch

x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad = True)
b = torch.randn(3,requires_grad = True)
z = torch.matmul(x,w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [3]:
print(z.grad_fn)
print(loss.grad_fn)

In [4]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.2671, 0.0210, 0.0368],
        [0.2671, 0.0210, 0.0368],
        [0.2671, 0.0210, 0.0368],
        [0.2671, 0.0210, 0.0368],
        [0.2671, 0.0210, 0.0368]])
tensor([0.2671, 0.0210, 0.0368])


In [5]:
z = torch.matmul(x,w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x,w)+b
print(z.requires_grad)

True
False


In [6]:
z = torch.matmul(x,w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [9]:
inp = torch.eye(4,5,requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out),retain_graph=True)
print(inp.grad)
out.backward(torch.ones_like(out),retain_graph=True)
print(inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(out),retain_graph =True)
print(inp.grad)

tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
