In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"random tensor: \n {x_rand}\n")

ones tensor:
 tensor([[1, 1],
        [1, 1]])

random tensor: 
 tensor([[0.8815, 0.2779],
        [0.7849, 0.1507]])



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random tensor\n{rand_tensor}\n")
print(f"ones_tensor \n {ones_tensor}\n")
print(f"zeros_tensor \n {zeros_tensor}\n")

random tensor
tensor([[0.7111, 0.2712, 0.2190],
        [0.8689, 0.4920, 0.1885]])

ones_tensor 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

zeros_tensor 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [7]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [8]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [11]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[:,0])
print(tensor[...,-1])
tensor[:,1] = 0
print(tensor)

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
t1 = torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

In [21]:
tensor = torch.rand(2,4)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1,"\n",y2)

tensor([[1.6597, 0.8256],
        [0.8256, 1.4393]]) 
 tensor([[1.6597, 0.8256],
        [0.8256, 1.4393]])


In [22]:
y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)
print(y3)

tensor([[1.6597, 0.8256],
        [0.8256, 1.4393]])


In [23]:
z1 = tensor*tensor
z2 = tensor.mul(tensor)

print(z1,"\n",z2)

tensor([[0.7393, 0.0095, 0.8380, 0.0729],
        [0.3594, 0.8776, 0.0122, 0.1901]]) 
 tensor([[0.7393, 0.0095, 0.8380, 0.0729],
        [0.3594, 0.8776, 0.0122, 0.1901]])


In [24]:
z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[0.7393, 0.0095, 0.8380, 0.0729],
        [0.3594, 0.8776, 0.0122, 0.1901]])

In [25]:
agg = tensor.sum()
print(agg,type(agg))
agg_item = agg.item()
print(agg_item,type(agg_item))

tensor(4.2255) <class 'torch.Tensor'>
4.225484848022461 <class 'float'>


In [26]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[0.8598, 0.0975, 0.9154, 0.2699],
        [0.5995, 0.9368, 0.1105, 0.4360]])
tensor([[5.8598, 5.0975, 5.9154, 5.2699],
        [5.5995, 5.9368, 5.1105, 5.4360]])


In [27]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [28]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [29]:
n = np.ones(5)
t = torch.from_numpy(n)

In [30]:
np.add(n,1,out=n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
